# Site settings
title: Data and Ethics
email: your-email@domain.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grocerystoreapple.github.io/connectorTemplate" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

#Course info

course_title_long: INFO 88 Data and Ethics
course_no: 41505
instructor: Anna Lauren Hoffmann
meeting_time: Tuesday 3:30 - 5:30 PM
location: 210 South Hall
units: 2
bcourse_url: https://bcourses.berkeley.edu/courses/1412776
course_page:

#Annoucements:
announcements:
  - Final Paper are due!
  - Office hours have been moved to Soda Hall for this week
  - Midterm regrades are due 4/15/16
  - "sign up: www.google.com"

#Schedule

schedule:
  module 1:
    description: "Situating 'Data' I: What is data?"##module title here
    time: 1/20
    reading:
      reading_1: 
        title: "Kitchin, R. (2014). Conceptualising Data."
        link: www.google.com
      reading_2:
        title: "Seltzer, W., & Anderson, M. (2001). The dark side of numbers (481-513)"
        link: www.facebook.com
    assignments: Short Writing Assignment no.1

  module 2:
    description: "Situating 'Data' II: A pre-history of data"##module title here
    time: 1/27
    reading:
      reading_1: 
        title: "Seltzer, W., &amp; Anderson, M. (2001). The dark side of numbers (481-513)"
        link: www.google.com
      reading_2:
        title: "Garber, M. (2014). Our numbered days: The evolution of the area code"
        link:
    assignments: Short Writing Assignment no.1

  module 3:
    description: "Ethical Toolbox II: Concepts of privacy and publicity"##module title here
    time: 2/10
    reading:
      reading_1: 
        title: "Tavani, H. (2012). Privacy and cyberspace. In Ethics and technology"
        link: www.google.com
      reading_2:
        title: "Barocas, S., &amp; Nissenbaum, H. (2014, November). Big data’s end run around procedural privacy protections"
        link:
    assignments: Short Writing Assignment no.1

